# application.yml
spring:
  profiles:
    active: dev #기본 설정을 DEV로
  # JPA 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # 개발 환경에서 스키마 자동 반영
    properties:
      hibernate:
        format_sql: true  # SQL 포맷 보기 좋게 출력
  sql:
    init:
      mode: always

server:
  port: 8080
